plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.5'
	id 'io.spring.dependency-management' version '1.1.4'
}

// 所有子模块的公共配置
allprojects {
	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	group = 'com.example'
	version = '1.0.0'
	sourceCompatibility = '17'

	repositories {

		mavenLocal()

		maven { url 'https://maven.aliyun.com/repository/public/' }
		maven { url 'https://maven.aliyun.com/repository/spring/'}
		maven { url 'https://maven.aliyun.com/repository/google/'}
		maven { url 'https://maven.aliyun.com/repository/gradle-plugin/'}
		maven { url 'https://maven.aliyun.com/repository/spring-plugin/'}
		maven { url 'https://maven.aliyun.com/repository/grails-core/'}
		maven { url 'https://maven.aliyun.com/repository/apache-snapshots/'}

		mavenCentral()
	}

	// 公共依赖（所有子模块共享）
	dependencies {
		implementation 'org.springframework.boot:spring-boot-starter'
		implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
		implementation 'org.springframework.boot:spring-boot-starter-web'
		implementation 'com.mysql:mysql-connector-j'
		compileOnly 'org.projectlombok:lombok:1.18.36'
		annotationProcessor 'org.projectlombok:lombok:1.18.36'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
	}

	// 测试配置
	test {
		useJUnitPlatform()
	}
}

dependencies {
	implementation ('org.springframework.boot:spring-boot-starter-data-jpa')
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.24'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'cn.dev33:sa-token-spring-boot3-starter:1.40.0'
	implementation ('org.apache.shardingsphere:shardingsphere-jdbc:5.5.2') {
		exclude group: 'org.apache.shardingsphere', module: 'shardingsphere-test-util'
		exclude group: 'com.google.protobuf', module: 'protobuf-java'
	}
	implementation 'org.antlr:antlr4-runtime:4.10.1'
	compileOnly 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'
	implementation 'com.mysql:mysql-connector-j'
	implementation 'com.alipay.sdk:alipay-easysdk:2.2.3'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
