spring:
  application:
    name: mask

  datasource:
    url: jdbc:mysql://localhost:3306/db_gpt?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true # ??false??????????sql??
    database: mysql
    database-platform: mysql
    hibernate.ddl-auto: update #???update?????????????????????????????????????create??????????????????????
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false

server:
  port: 8081